version: "3.7"

services:
  proxy:
    build: ./nginx
    container_name: proxy
    ports:
      - 80:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

  web1:
    build: ./web1
    container_name: web1
    ports:
      - 8080:80

  web2:
    build: ./web2
    container_name: web2
    ports:
      - 8081:80
